loong:
  datasource:
    host: 127.0.0.1
    username: root
    password: root
  rabbitmq:
    host: localhost
    username: loong
    password: loong
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis


#logging:
#  level:
#    root: trace