server:
  servlet:
    context-path: /${spring.application.name}
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB