CREATE DATABASE loong_iam CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE DATABASE loong_data CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE DATABASE loong_crm CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE DATABASE loong_scm CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE DATABASE loong_camunda CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
