spring:
  rabbitmq:
    port: 5672
    virtualHost: loong
  cloud:
    function:
      definition: |
        loongLogFunction;loongLogConsumer;
    stream:
      bindings:
        loongLogProducer:
          destination: loong-log-producer-topic
        loongLogFunction-in-0:
          destination: loong-log-producer-topic
          group: loong-log-group
        loongLogFunction-out-0:
          destination: loong-log-function-topic
        loongLogConsumer-in-0:
          destination: loong-log-function-topic
          group: loong-log-group

